<a href="https://colab.research.google.com/github/manasik29/EDA/blob/main/Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- Univariate Feature Selection
- RFE - Recursive Feature Elimination
- Feature Importance Using Decision Tree

**Univariate Feature Selection**

In [4]:
import pandas as pd
from sklearn.feature_selection import SelectKBest
from numpy import set_printoptions
from sklearn.feature_selection import chi2
filename = 'pima-indians-diabetes.data.csv'
names= ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
df = pd.read_csv(filename, names=names)

In [5]:
df

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

In [6]:
array = df.values
X = array[:,0:8]
Y = array[:, 8]

In [7]:
#feature extraction
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X,Y)

In [8]:
#summarize scores
set_printoptions(precision=3)
print(fit.scores_)
#features = fit.transform(X)

[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]


In [9]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

**RFE - Recursive Feature Elimination**

In [10]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [16]:
model = LogisticRegression(max_iter=400)
rfe = RFE(model)
fit = rfe.fit(X,Y)

In [17]:
fit.n_features_

4

In [18]:
fit.support_

array([ True,  True, False, False, False,  True,  True, False])

In [19]:
fit.ranking_

array([1, 1, 3, 5, 4, 1, 1, 2])

In [20]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

**Feature Importance Using Decision Tree**

In [24]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X,Y)

DecisionTreeClassifier()

In [25]:
print(model.feature_importances_)

[0.065 0.326 0.105 0.019 0.029 0.217 0.121 0.117]


In [26]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']